# Generated by Django 3.2 on 2022-08-30 18:58

import django.db.models.deletion
from django.db import migrations, models

import mailing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_on",
                    models.DateTimeField(help_text="When delivery should start"),
                ),
                ("text", models.CharField(blank=True, max_length=90, null=True)),
                ("filtering", models.JSONField(null=True)),
                (
                    "stop_mailing_by",
                    models.DateTimeField(
                        help_text="By which time delivery should stop"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When it was created [autogen]"
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("sending", "sending"),
                            ("sent", "sent"),
                            ("recieved", "recieved"),
                            ("delivery_error", "delivery_error"),
                        ],
                        default=mailing.models.DeliveryStatus["DRAFT"],
                        max_length=64,
                    ),
                ),
                (
                    "client_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_message",
                        to="clients.client",
                    ),
                ),
                (
                    "mailing_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_message",
                        to="mailing.mailinglist",
                    ),
                ),
            ],
        ),
    ]
