# Generated by Django 3.2 on 2022-09-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglist",
            name="filtering",
            field=models.JSONField(default={}),
        ),
    ]
