# Generated by Django 3.2 on 2022-09-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_mailinglist_filtering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglist",
            name="filtering",
            field=models.JSONField(default=dict),
        ),
    ]
